# Generated by Django 6.0.5 on 2026-06-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('pending', 'To-Do'), ('ongoing', 'In-Progress'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
