# Generated by Django 6.0.6 on 2026-06-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_tasks_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="due_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
