# Generated by Django 6.0.6 on 2026-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_tasks_due_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
